name: Mantener backend despierto

on:
  schedule:
    - cron: '*/10 10-23,0-1 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping al backend
        run: curl -s https://ecommerceapi-user.onrender.com/api/productos > /dev/null